sudo: false

language: php

matrix:
  fast_finish: true
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
      dist: precise
    - php: 5.5
      dist: precise
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4snapshot
    - php: nightly
  allow_failures:
    - php: nightly

before_script:
  - if [[ "$SNIFF" == "1" ]]; then composer self-update; fi
  - if [[ "$SNIFF" == "1" ]]; then composer require squizlabs/php_codesniffer:dev-master; fi
  - composer install
  - phpenv rehash

script:
  - composer test
  - if [[ "$SNIFF" == "1" ]]; then vendor/bin/phpcs . --standard=./custom-ruleset.xml; fi
